### ISSUE TITLE
Cross platform components?

### ISSUE THREAD

**Issue by KjellConnelly** [elias-sundqvist/obsidian-react-components#18]
I'm just wondering if there is a workflow to write cross platform components (ie write in `.jsx` files, which can be compiled with webpack or whatever for the browser, as well as work within this plugin?

For example, I might want to have a vault which has react components in it, but if I use `obsidian-publish`, or write my own code to generate websites via markdown files, I want to make sure the react components render the same. 

Also would be nice to write code within a proper IDE as opposed to within Obsidian `.md` files.

Even just a template for a `.jsx` file, and a script which creates a markdown file which `obsidian-react-components` can handle. That way I can test in browser, with hot reload or whatever, syntax highlighting, linting, typescript, or whatever. And then generate markdown files for it that work in obsidian?

**Comment by elias-sundqvist** [comment]
I'm not sure if I completely understood your requirements, but here are some thoughts: 

Regarding making components that work both for the plugin and elsewhere - one option is to make a github repo with your components and add them to [npm](https://www.npmjs.com/). Then you can access the components in your vault using [skypack](https://www.skypack.dev/). 

You could then create components like this in your component folder 
```tsx
// ACoolComponent.md
import { ACoolComponent as Component } from 'https://cdn.skypack.dev/KjellConnelly/obsidian-components';
return <Component {...props}/>
```

Regarding syntax highlighting and autocomplete - you can get some of this functionality by opening the .md file in visual studio code and selecting the `TypeScript React`  language mode. 


I've also been thinking about adding direct support for .jsx and .tsx files in the plugin, and making a separate obsidian plugin for IDE-style code editing. I'm not sure if/when I'll be done with that though.

**Comment by KjellConnelly** [comment]
Thank you so much for the reply :) I didn't even know about sky pack which sounds amazing! I'll have to try your suggestions!
