### ISSUE TITLE
Test that the plugin works on Linux

### ISSUE THREAD

**Issue by elias-sundqvist** [elias-sundqvist/obsidian-react-components#2]

**Comment by lucasew** [comment]
Tested with the following note snippet

https://gist.github.com/lucasew/089e59411e61ccceaca7b5a6388203e5

What a mind-blowing thing.

I am running NixOS [1]

It works in a cross-platform way so it should work anywhere a recent browser is supported so not a problem for obsidian desktop at least. Non portable things can happen if you use a non portable system function via node API but it's out of scope of this.

If obsidian did not have cors issues it will be perfect.

[1] System definition (acer-nix) commit:  https://github.com/lucasew/nixcfg/commit/96cd7cbea5b4283bc3f0f47ec843eb1305ac938d

**Comment by elias-sundqvist** [comment]
Thank you for confirming that it works :)
