### ISSUE TITLE
New release doesn't work

### ISSUE THREAD

**Issue by KjellConnelly** [elias-sundqvist/obsidian-react-components#20]
Hi! Sorry to bother you again, but I see your made a new release an hour ago, but it looks like the github release has a 0.1.0 tag, while there are no new assets attached to that tag. So upgrading/downloading the plugin from obsidian results in an error.

**Comment by elias-sundqvist** [comment]
Yeah, the github build action is stuck for some reason. It might just be a temporary thing. Not sure what causes the problem.

**Comment by elias-sundqvist** [comment]
I can remove the tag for now and try to restart the build tomorrow.

**Comment by elias-sundqvist** [comment]
Re-running the action on previous successful builds also seems to fail, so there's nothing special about the new release at least...

**Comment by elias-sundqvist** [comment]
Seems like the issue is with some updated dependency. I could reproduce the issue locally by reinstalling all node modules.

**Comment by elias-sundqvist** [comment]
Managed to fix it by downgrading to typescript 4.2.4 in package.json :)

**Comment by KjellConnelly** [comment]
Nice ty ty :) I cloned, built, and moved main.js and manifest while I was hanging out yesterday :)
