### ISSUE TITLE
Markdown component is not rendering markdown like Obsidian does

### ISSUE THREAD

**Issue by Reenuay** [elias-sundqvist/obsidian-react-components#25]
First of all let me thank you for such great tool! I really enjoy how simple is using it in Obsidian and taking it from just note taking app to powerful instrument that can do pretty much everything!

Coming to my question (I don't know if it's an issue), I use Markdown component for complex things like embeding one notes into another ones programmatically. Markdown is processed correctly as I can reason, but at the end not all of the useful things that Obsidian provides are there. For example embeds are not pasted into rendered view. Doing `<Markdown src="![[SomeNote]]" />` will give you only empty span with `SomeNote` text inside it, but will not embed SomeNote's content in it. I know that it is possible to do this theoretically, because Dataview plugin doing this pretty well. Of course, I don't know what difficulties are behind this. Maybe I'm just missing something. Can you suggest me some workaround for it, please?

**Comment by elias-sundqvist** [comment]
The function for rendering markdown does not process embeds except under certain circumstances. 

I can fake the process  manually, but I don't think it will work well with all plugins. 

I have made this work around. But I also noticed that the live preview support is a bit broken in the latest obsidian version, so I think I will try to fix that before releasing any new update.

**Comment by elias-sundqvist** [comment]
This issue should now be resolved in the latest update (0.1.6)

**Comment by Reenuay** [comment]
> This issue should now be resolved in the latest update (0.1.6)

Wow! Great! Everything works just fine! Thank you!
